- name: "update packages."
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "install dependencies."
  become: true
  apt: 
    name: [ "unzip"]
    state: latest
    update_cache: true

- name: "install node/npm"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: "install libcap2-bin"
  shell: |
    sudo apt-get install libcap2-bin

- name: "configure port bind"
  shell: |
    sudo setcap cap_net_bind_service=+ep /usr/local/bin/node

- name: "install pm2."
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

  