- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: "copy files."
  become: true
  copy:
    src: /root/project/backend.zip
    dest: /tmp

- name: "unzip folder."
  become: true
  unarchive:
    src: /tmp/backend.zip
    dest: /home/ubuntu
    remote_src: yes

- name: "make .env file"
  become: true
  shell: mv .env.main .env chdir=/home/ubuntu/backend

- name: "start node application"
  become: true
  shell: node dist/main.js chdir=/home/ubuntu/backend
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: postgres-udacity.c1pkw7dekdff.eu-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgresuser
    TYPEORM_PASSWORD: passpostgres
    TYPEORM_DATABASE: postgresdb

- name: Start Pm2 service
  become: true
  command: pm2 start dist/main.js --name app chdir=/home/ubuntu/backend
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: postgres-udacity.c1pkw7dekdff.eu-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgresuser
    TYPEORM_PASSWORD: passpostgres
    TYPEORM_DATABASE: postgresdb