- name: "copy files."
  become: true
  copy:
    src: /root/project/backend.zip
    dest: /tmp

- name: "unzip folder."
  become: true
  unarchive:
    src: /tmp/backend.zip
    dest: /home/ubuntu
    remote_src: yes

- name: "install npm packages"
  command: sudo npm install
  args: 
    chdir: /home/ubuntu/backend

- name: "build backend"
  command: sudo npm run build 
  args:
    chdir: /home/ubuntu/backend

- name: "start Pm2 service"
  command: pm2 start ./dist/main.js --name app 
  args:
    chdir: /home/ubuntu/backend
  environment:
    ENVIRONMENT: production
    NODE_ENV: local
    VERSION: 1
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: postgres-udacity.c1pkw7dekdff.eu-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgresuser
    TYPEORM_PASSWORD: passpostgres
    TYPEORM_DATABASE: postgres

- name: "run application as service"
  shell: |
    sudo env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu