- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: "copy env file."
  become: true
  copy:
    src: /root/project/backend/.env.main
    dest: /home/ubuntu

- name: "copy dist files."
  become: true
  copy:
    src: /root/project/backend/dist.zip
    dest: /tmp

- name: "unzip dist folder."
  become: true
  unarchive:
    src: /tmp/dist.zip
    dest: /home/ubuntu
    remote_src: yes

- name: Start Node App
  become: true
  command: pm2 start main.js --name app chdir=/home/ubuntu/dist
    