- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: "copy files."
  become: true
  copy:
    src: /root/project/backend.zip
    dest: /tmp

- name: "unzip dist folder."
  become: true
  unarchive:
    src: /tmp/backend.zip
    dest: /home/ubuntu
    remote_src: yes

- name: Start Node App
  become: true
  command: pm2 start dist/main.js --name app chdir=/home/ubuntu/backend
    